[package]
name = "history"
version = "0.1.0"
edition = "2024"

[dependencies]
storage = {
    path = "../storage"
}

pookie-core = {
    path = "../pookie-core"
}

pookie-clipboard = {
    path = "../pookie-clipboard"
}

sqlx = {
    version = "0.8",
    features = [
        "runtime-tokio",
        "sqlite"
    ]
}